// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQpl0FvC550CobPEj4oCsadOydVd5gaXk',
    appId: '1:207511953360:web:82e93e6033d61a3ae663d5',
    messagingSenderId: '207511953360',
    projectId: 'cure-home-care',
    authDomain: 'cure-home-care.firebaseapp.com',
    storageBucket: 'cure-home-care.firebasestorage.app',
    measurementId: 'G-4Z49MN0Z03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZq5evKt43-RTfQ5WesRo6deWpVj-tJ8',
    appId: '1:207511953360:android:1bedcba3060c4780e663d5',
    messagingSenderId: '207511953360',
    projectId: 'cure-home-care',
    storageBucket: 'cure-home-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa77vWE2bJLVOcvR91_AwgLs0KUltMq60',
    appId: '1:207511953360:ios:dc6ecdf3eedc278be663d5',
    messagingSenderId: '207511953360',
    projectId: 'cure-home-care',
    storageBucket: 'cure-home-care.firebasestorage.app',
    iosBundleId: 'com.example.cureHomeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa77vWE2bJLVOcvR91_AwgLs0KUltMq60',
    appId: '1:207511953360:ios:dc6ecdf3eedc278be663d5',
    messagingSenderId: '207511953360',
    projectId: 'cure-home-care',
    storageBucket: 'cure-home-care.firebasestorage.app',
    iosBundleId: 'com.example.cureHomeCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQpl0FvC550CobPEj4oCsadOydVd5gaXk',
    appId: '1:207511953360:web:0823a6eddc4c02dfe663d5',
    messagingSenderId: '207511953360',
    projectId: 'cure-home-care',
    authDomain: 'cure-home-care.firebaseapp.com',
    storageBucket: 'cure-home-care.firebasestorage.app',
    measurementId: 'G-HCGJ7NFCBS',
  );
}
